Add 3 new Badges.
BraveUX/for-the-badge pull request #92
Opened 2019-08-03 15:52 UTC by ashawe

Works on | My Machine ( #91 )
Made with | Out Pants ( #86 )
Not a Bug | A Feature

2019-08-03 16:38 UTC, ashawe commented
I can't understand why I can't preview the files on GitHub.

2020-05-25 12:31 UTC, DarkWiiPlayer commented
I'd use at least 5 of these; is there any reason for not merging this already?

2020-05-29 10:09 UTC, ashawe commented
@DarkWiiPlayer I don't know man. This repo is inactive

2020-07-21 03:39 UTC, ashawe commented
I noticed that a few hours ago some commits were made. I want to know why any PR's are not being accepted

2020-09-08 17:13 UTC, ekfuhrmann requested changes
Thank you so much for taking the time to submit this PR. First and foremost, apologies for the long lapse in handling the PR's.

I ask that you make the changes requested, and I'll get to adding it to the project as soon as possible.

For the record, I'm a big fan of a lot of these badges, so thank you for the contribution!

2020-09-08 17:13 UTC, ekfuhrmann commented on src/images/badges/ctrl_c_ctrl_v.svg
> +<?xml version="1.0" encoding="utf-8"?>
Please set the font color to white to work more consistently with other badges.

![image](https://user-images.githubusercontent.com/8878152/92506714-da3c4d80-f1d3-11ea-935a-067156ae07eb.png)

2020-09-08 17:13 UTC, ekfuhrmann commented on src/images/badges/fixed-bugs.svg
> +<?xml version="1.0" encoding="utf-8"?>
Please set the font color to white to work more consistently with other badges.

![image](https://user-images.githubusercontent.com/8878152/92506765-f04a0e00-f1d3-11ea-9a41-688c0bdd96a5.png)

2020-09-08 17:13 UTC, ekfuhrmann commented on src/images/badges/it-works-why.svg
> +<?xml version="1.0" encoding="utf-8"?>
Please set the font color to white to work more consistently with other badges.

![image](https://user-images.githubusercontent.com/8878152/92506821-0788fb80-f1d4-11ea-97b0-8e99f0dbb980.png)

2020-09-08 17:13 UTC, ekfuhrmann commented on src/images/badges/made-with-out-pants.svg
> +<?xml version="1.0" encoding="utf-8"?>
Please set the font color to white, and the background color to `#ef4041` to work more consistently with other badges.

![image](https://user-images.githubusercontent.com/8878152/92506856-166fae00-f1d4-11ea-940d-905cf1ff8d21.png)

2020-09-08 17:13 UTC, ekfuhrmann commented on src/images/badges/not-a-bug-a-feature.svg
> +<?xml version="1.0" encoding="utf-8"?>
Please set the font color to white, and the background color to #ef4041 to work more consistently with other badges.

In addition make sure you use the correct typography as outlined in the readme for the `A FEATURE` portion of the badge.

![image](https://user-images.githubusercontent.com/8878152/92507077-6e0e1980-f1d4-11ea-8aaa-5796807d78bf.png)

2020-09-08 17:13 UTC, ekfuhrmann commented on src/images/badges/open-source.svg
> +<?xml version="1.0" encoding="utf-8"?>
Please set the font color to white, and the background color to #ef4041 to work more consistently with other badges.

![image](https://user-images.githubusercontent.com/8878152/92507257-b0375b00-f1d4-11ea-837e-6b4aaafdd254.png)

2020-09-10 14:08 UTC, ekfuhrmann commented on src/images/badges/open-source.svg
>  	 viewBox="0 0 160.7 35.1" style="enable-background:new 0 0 160.7 35.1;" xml:space="preserve"  width="160.6" height="35">
Type looks to not be center aligned.

2020-09-10 14:11 UTC, ekfuhrmann commented on src/images/badges/fixed-bugs.svg
>  <rect x="69.5" y="0" class="st0" width="70.6" height="35"/>
Type looks to not be center aligned.

2020-09-10 14:12 UTC, ekfuhrmann commented on src/images/badges/ctrl-c-ctrl-v.svg
>  <g>
Type looks to not be center aligned, and the R for the first `CTRL` seems to be of the wrong typeface. It should be `Roboto Medium`.

2020-09-10 14:13 UTC, ekfuhrmann requested changes
Thank you so much for taking the time to update these. There are a few minor issues with a couple of the badges that I left comments on. Otherwise everything else is looking good. If you could make those adjustments I'll add this to the site.

Thanks again for the support!

2020-09-10 18:32 UTC, ekfuhrmann approved these changes

2020-09-10 18:35 UTC, ekfuhrmann commented
Looks great, thanks for taking the time to create and update these badges!

2020-09-10 18:35 UTC, merged